
spring:

  task:
    scheduling:
      pool:
        size: 1
  # jackson config
  jackson:
    serialization:
      write-dates-with-context-time-zone: true
      write-dates-as-timestamps: false
      write-enums-using-to-string: false
   # property-naming-strategy: SNAKE_CASE

  # datasource config
  datasource:
    hikari:
      schema: app
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      auto-commit: true
      maximum-pool-size: 20
    url: jdbc:postgresql://localhost:5432/trading-bot

  # JAP config
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: app

  config:
    import: private-config.yml

# management config
management:
  endpoints:
    web:
      exposure:
        include: heath, prometheus, info, metric
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true


# server config
server:
  port: 8081

telegram:
  chatID: 852348061
  name: MTCCurrencyBot

test:
  trading:
    gain: 0.9
    deposit: 20
    minDeposit: 12
    balance: 200

trading:
  gain: 0.5
  taker: 0.1
  maker: 0.1
  deposit: 15
  criticalLostTimeForBuying: 3
  criticalLostPercentage: 3









