#fake account
#binance:
  #apiKey: C8vd0MExSc0BAQuQfLnTdFirQuxvtLB9zjEte6D1g8NS54vrUWIds7Gmi2vF681d
  #secretKey: 2SSsrmYgnQFk9gWPi7kCkK5ylq6WVjEGFTkcczpgvFvABwuP0uOWTyN56nzlf5st

binance:
  apiKey: 5HuOTl8uyFXdbXGmLfQjxam8Cmsd76Q6Fsaz5aCoHXpBBFQvFnDDnsCm9129ceFb
  secretKey: MssC9TgPjLzYOz0Xf4lRq3tF8REALWtX9vun13DligrVdGHthIeDk74y1iZlko3E


telegram:
  token: 6502879208:AAHlbkMm5w1BmRokuiN2ACq0FpfAJMG_WUw