#fake account
#binance:
  #apiKey: C8vd0MExSc0BAQuQfLnTdFirQuxvtLB9zjEte6D1g8NS54vrUWIds7Gmi2vF681d
  #secretKey: 2SSsrmYgnQFk9gWPi7kCkK5ylq6WVjEGFTkcczpgvFvABwuP0uOWTyN56nzlf5st

binance:
  apiKey: secret
  secretKey: secret


telegram:
  token: 6502879208:AAHlbkMm5w1BmRokuiN2ACq0FpfAJMG_WUw
