package by.zemich.binancebot.core.enums;

public enum EBargainStatus {
    NEW,
    OPEN_BUY_ORDER_CREATED,
    OPEN_BUY_ORDER_FILLED,
    OPEN_SELL_ORDER_CREATED,
    OPEN_SELL_ORDER_FILLED,
    CANCELED_BUY_ORDER_WAS_EXPIRED,
    CANCELED_IN_THE_RED,
    COMPLETED_SUCCESSFULLY;

}
