package by.zemich.binancebot.core.enums;

public enum EEventType {
    ASSET_WAS_SOLD,
    BUY_LIMIT_ORDER_WAS_PLACED,
    SELL_LIMIT_ORDER_WAS_PLACED,
    STOP_LIMIT_ORDER_WAS_PLACED,
    ENDPOINT_WAS_FOUNDED,
    ASSET_WAS_BOUGHT,
    BARGAIN_WAS_CREATED,
    BARGAIN_WAS_CANCELED,
    ERROR;

}
